# Generated by Django 4.2.3 on 2023-08-08 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('price', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('year', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('millage', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('fuel_type', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('transmission', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('horsepower', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('color', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('moreInformation', models.CharField(blank=True, default='', max_length=3000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MainImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(default='', max_length=255)),
                ('car', models.ForeignKey(default='', max_length=255, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Car.car')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='main_image',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Car.mainimage'),
        ),
    ]
